version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy_production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku production
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/hammayoun-safi.git master
workflows:
  version: 2.1
  build-deploy-production:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
